# Generated by Django 4.0.3 on 2022-08-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_appointment_date_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
